CREATE TABLE `clients` (
  `id` int NOT NULL,
  `numero_client` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  `raison_sociale` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `adresse` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `code_postal` varchar(10) COLLATE utf8mb4_general_ci NOT NULL,
  `ville` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `adresse_livraison` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `livraison_identique` tinyint(1) DEFAULT '0',
  `siret` varchar(14) COLLATE utf8mb4_general_ci NOT NULL,
  `numero_tva` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `depot_mode` enum('espece','cheque','virement','paiement_carte') COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'espece',
  `nom_dirigeant` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `prenom_dirigeant` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `telephone1` varchar(20) COLLATE utf8mb4_general_ci NOT NULL,
  `telephone2` varchar(20) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `parrain` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `offre` enum('packbronze','packargent') COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'packbronze',
  `date_creation` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_dajout` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `pdf1` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `pdf2` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `pdf3` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `pdf4` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `pdf5` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `pdfcontrat` varchar(255) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `iban` varchar(34) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_clients_numero` (`numero_client`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci